### ISSUE TITLE
Failed to get album metadata

### ISSUE THREAD

**Issue by dr01dy** [Sorrow446/Nugs-Downloader#10]
Item failed.
Get "https://streamapi.nugs.net/api.aspx?containerID=30781&method=catalog.container&vdisp=1": x509: certificate signed by unknown authority

**Comment by jjacobu** [comment]
Try: nugs_dl_x64.exe "https://play.nugs.net/#/catalog/recording/30781", that is working for me.
The containerID 30781 needs to be in the play.nugs.net format so the playlist can be obtained

**Comment by Sorrow446** [comment]
Temporary certificate problem on Nugs' side.
