### ISSUE TITLE
"API didn't return a video manifest URL"

### ISSUE THREAD

**Issue by neilyboy** [Sorrow446/Nugs-Downloader#15]
Everything looks good to me yet while trying to snag a video I get 

`Nugs-Downloader-main>nugs_dl_x64.exe https://play.nugs.net/#/exclusive-livestreams/container/32120

 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
          |___|

Signed in successfully - One month

Item 1 of 1:
Goose - 04/15/23 The Salt Shed, Chicago, IL
Item failed.
The API didn't return a video manifest URL.`

Any help would be appreciated! I would love to get this to work for simplicity ;)

tried with other url as well
https://play.nugs.net/#/videos/artist/1205/Goose/container/32120

edit.. I was only able to find my token when I went to this url vs the one in your token.md
"https://get.nugs.net/account/subscription"

thanks again for any help you can provide!! I appreciate ya!

**Comment by Sorrow446** [comment]
Haven't touched this in a bit because they've been forcing DRM on most stuff, but wouldn't mind looking into this problem. Have you got a Reddit or Discord we could talk over?

**Comment by neilyboy** [comment]
Discord - @neilyboy#2714

**Comment by Sorrow446** [comment]
Send me a friend request, username's the same.

**Comment by neilyboy** [comment]
I shot you a friend request! Thanks again!
I am getting 'The API didnt return a track stream URL' for audio and 'The API didnt return a video manifest url' for video

thanks again for any help or direction you can provide.

**Comment by Sorrow446** [comment]
Fixed https://github.com/Sorrow446/Nugs-Downloader/commit/4c33b67d77b66af5f71cd64dd839a6ac67139eef.

**Comment by Sorrow446** [comment]
Fixed https://github.com/Sorrow446/Nugs-Downloader/commit/4c33b67d77b66af5f71cd64dd839a6ac67139eef.
