### ISSUE TITLE
Windows Defender Identifying x64 exe as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by angeloalberico** [Sorrow446/Nugs-Downloader#17]
All of the sudden when I try to run the app I get a windows defender message saying the app is a severe threat and I can't do anything with the app now.  I'm sure windows defender updated it's signatures recently.

Trojan:Win32/Wacatac.B!ml
![error message](https://github.com/Sorrow446/Nugs-Downloader/assets/16217985/9baf125f-ef2e-46dc-888f-945ff86ed987)

**Comment by winebob** [comment]
Same here.

**Comment by Sorrow446** [comment]
AV software has never liked compiled Go binaries :/. You could either disable Defender temporarily or try running from source code.
`
go run main.go structs.go https://play.nugs.net...`
