### ISSUE TITLE
anyway to exclude formats?

### ISSUE THREAD

**Issue by live-music-guy** [Sorrow446/Nugs-Downloader#18]
thanks for  very useful tool

would like to DL in flac16 where available as opposed to 24bitMQA

however some links are available in HLS-only, where AAC is the only option

is it possible to specify FLAC16 as default with AAC as a fallback, without 24bit MQA being an option

another great feature would be the ability to append format to folder name

<foldername>.FLAC16 or <foldername>.AAC, etc.

**Comment by Sorrow446** [comment]
You're welcome. They actually only had AAC for HLS-only tracks when I last checked.

Yep, you can change these lines from line 87:
```go
var trackFallback = map[int]int{
	1: 2,
	2: 5,
	3: 2,
	4: 3,
}
```
to:
```go

var trackFallback = map[int]int{
	1: 5,
	2: 5,
	3: 2,
	4: 3,
}
```

The format templates could be done, have done templates for many of my other tools before.

**Comment by Sorrow446** [comment]
We can talk about that over Discord.
