### ISSUE TITLE
Failed to get Metadata

### ISSUE THREAD

**Issue by Theuptownruler** [Sorrow446/Nugs-Downloader#19]
When downloading newly released shows over the past week I am getting a "failed to get metadata" on certain tracks. Anywhere from 1 to 5 tracks of a show don't download.
This is the error

Failed to get track stream metadata.
Track failed.
Get "https://streamapi.nugs.net/bigriver/subPlayer.aspx?app=1&endDateStamp=1689299249&nn_userID=2381401&platformID=1&startDateStamp=1686707249&subCostplanIDAccessList=nntrlhqmonthly&subscriptionID=" - - - - - - - "&trackID=581209": EOF

**Comment by Theuptownruler** [comment]
Source code
This whole shole won't download
[https://play.nugs.net/#/catalog/recording/33095

**Comment by Sorrow446** [comment]
Working here. Could you send the whole get URL?

**Comment by Theuptownruler** [comment]
This is on Android but same thing happens o' windows machine

And it continues for all tracks

go run  main.go structs.go https://play.nugs.net/#/catalog/recording/33095

 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
          |___|

Signed in successfully - HiFi Streaming

Item 1 of 1:
Widespread Panic - 06/24/23 Red Rocks Amphitheatre, Morrison, CO
Failed to get track stream metadata.
Track failed.
Get "https://streamapi.nugs.net/bigriver/subPlayer.aspx?app=1&endDateStamp=1689299249&nn_userID=2381401&platformID=7&startDateStamp=1686707249&subCostplanIDAccessList=nntrlhqmonthly&subscriptionID=" - - - - - - - - "&trackID=583279": EOF
Failed to get track stream metadata.
Track failed.

**Comment by Sorrow446** [comment]
Could be a network or account issue. Could you send me your credentials over Discord? Username's the same as on here.

**Comment by Theuptownruler** [comment]
I am using the July 22 build could that be the issue. Didn't know there was
a new build.. Will do in a few.

**Comment by Sorrow446** [comment]
Reminding you.

**Comment by Theuptownruler** [comment]
Everything seems to be working fine now. Not sure what it was but I did
update to latest build. Thanks for your help it's appreciated
