### ISSUE TITLE
Downloading in FLAC-HD? (24-bit FLAC)

### ISSUE THREAD

**Issue by kickturn** [Sorrow446/Nugs-Downloader#2]
How would I download an album to FLAC-HD or ALAC-HD? I don't want a MQA file.

**Comment by Sorrow446** [comment]
They don't have non-MQA 24-bit.

**Comment by kickturn** [comment]
Is that saying you can't fetch FLAC-HD from the subscription?

**Comment by Sorrow446** [comment]
Yep. The only way's to actually buy them. I know it's frustrating.

**Comment by kickturn** [comment]
Alright, thanks for clarifying.
