### ISSUE TITLE
Mac Ventura M1 chip

### ISSUE THREAD

**Issue by vcifello** [Sorrow446/Nugs-Downloader#23]
Mac arm64 binary
"zsh killed" persists

Tried every way I could find to get this to run.

Any ideas?

**Comment by Sorrow446** [comment]
Not sure about Mac, sorry. Better off building/running from source.
`go build main.go structs.go`
`go run main.go structs.go <args>...`

**Comment by gdog1078** [comment]
A little buggy but I got 2 4k DLs.

**Comment by gdog1078** [comment]
Technically it's was Sonoma beta.

**Comment by vcifello** [comment]
Thanks for the responses and especially to Sorrow for creating this tool!! I thinks it is a Mac Ventura  issue which is totally locked down to unsigned executables.

I wound up embedding the linux executable in a docker container :)

In case anyone wants to do this in the future

put the config.json (change outPatrh to Nugsdownloads) in the same folder as Dockerfile

Dockerfile
FROM alpine as build-env
RUN apk add --no-cache build-base
WORKDIR /app
COPY . .

FROM alpine

ENV url_to_download default_url

COPY --from=build-env /app/ /app/
WORKDIR /app
RUN chmod +x /app/nugs_dl_arm64
CMD /app/nugs_dl_arm64 $url_to_download

Build the image:

docker build -t vinnugs:latest . 

Run the container and pass the url to download:

docker run -v ./downloads:/app/Nugsdownloads -e url_to_download=[PUT_URL_HERE] vinnugs:latest          

this will create a downloads folder in the current directory and save the output there.

**Comment by vcifello** [comment]
Building from source, as suggested above, works.

Thank you :)
