### ISSUE TITLE
Allow FLAC-HD (24-bit / 96khz) downloads as a format

### ISSUE THREAD

**Issue by werkkrew** [Sorrow446/Nugs-Downloader#24]
In addition to MQA can you please add the FLAC-HD (true 24-bit FLAC) as one of the formats which can be selected? For my purposes MQA is not acceptable as a 24-bit format.

Thanks!

**Comment by Sorrow446** [comment]
I know MQA sucks, but they don't have 24-bit regular FLAC for streaming, purchase only :(.
