### ISSUE TITLE
Google as auth provider?

### ISSUE THREAD

**Issue by jhershberg** [Sorrow446/Nugs-Downloader#3]
Hi, is there a way for me to use this if my nugs account uses google as the auth provider and I therefor have no password?

**Comment by Sorrow446** [comment]
Not currently because of reCAPTCHA and how much work it is to automate it. Using cookies could work fine, though. Will look into it tonight.

**Comment by Sorrow446** [comment]
You can auth with Apple and Google accounts with tokens now. I won't implement auth with credentials; too much work.
https://github.com/Sorrow446/Nugs-Downloader/commit/168c4851167420ebe0a8ecff0adc6adf0f23a5c8
