### ISSUE TITLE
Livestream Download is failing

### ISSUE THREAD

**Issue by github487578** [Sorrow446/Nugs-Downloader#31]
Noticed they changed their video streaming in the last few days and they are now embedded. 

When i try to use a link similar to this https://play.nugs.net/livestream/34116/exclusive the downloaded fails with an invalid URL. 

Tried every combo i could think of:
- removing exlusive
- wrap in quotes
- wrap in double quotes
- - and probably several other combos.

**Comment by davidfries** [comment]
I'm still able  to download a playlist if I parse out the parameters of the new URL and paste into the old. This sadly doesn't work for videos like the below example.

`.\nugs_dl_x64.exe "https://play.nugs.net/#/videos/artist/1245/Goose/container/33838"` 

`Item 1 of 1:
Item failed.
no video available`

**Comment by Sorrow446** [comment]
What do you mean by embedded? The downloader doesn't scrape at all, FYI, all API calls for meta.
