### ISSUE TITLE
Only audio is downloaded when a release has both audio and video

### ISSUE THREAD

**Issue by eymtkzwt** [Sorrow446/Nugs-Downloader#33]
Firstly, thank you for your work on this! It's an amazing tool.

When I download a release that has both audio and video, the application seems to only download the audio portion. Is there something I can do to make it grab both, or is this a feature that isn't available? I'm running the latest commit https://github.com/Sorrow446/Nugs-Downloader/commit/45943db42b4013661edcc84c05c93a910c2bcb42 on Windows, and video-only releases download fine

An example is this release: https://play.nugs.net/release/27319

Thanks!

**Comment by Sorrow446** [comment]
You're welcome, thank you. I didn't know these could co-exist. I'll have to implement a flag like `-v` that'll tell the tool to choose the video instead. Won't take me long to do.

**Comment by Sorrow446** [comment]
Done. Gonna keep this issue open in case you have an issue.

**Comment by eymtkzwt** [comment]
It works for individual releases now (thanks!), but it doesn't seem to work when I download an entire artist's catalog. Is this also possible? I'd like to run the initial command to download all audio, and then use the same command with -v to go back through and download all video.

For example, this release will download as video as expected when using -v https://play.nugs.net/release/26588
But when I try to download the artist's entire video catalog with -v https://play.nugs.net/artist/1198, it only downloads the audio portion.

I tried looking into the code myself, but it's above my skill level XD

**Comment by Sorrow446** [comment]
So the tool ignores the two under the videos section on that artist page? No probs, it's likely that the metadata endpoint just wants a param to include the videos as well. I'll do this soon.

**Comment by eymtkzwt** [comment]
Correct, it downloads the audio track for each of those releases, but ignores the video.

**Comment by Sorrow446** [comment]
Please try. https://pastebin.com/raw/fZ7RHb4J
The artist meta doesn't contain any product info which is needed for the videos, so I've had to have the tool just take the container ID from each item, then have the album function fetch the metadata again with the product info. Is inefficient, but this is the only way.

**Comment by eymtkzwt** [comment]
That seems to do the trick! I can now download an artist's entire audio library and then go back through and get the video with the -v option

**Comment by Sorrow446** [comment]
Glad we sorted it. Just pushed the update. You can use `--skip-videos` if you wanna skip the video-only releases.
