### ISSUE TITLE
Can't get Exclusive Livestream to dl.

### ISSUE THREAD

**Issue by Cryptical1** [Sorrow446/Nugs-Downloader#34]
Can't get Exclusive Livestream to dl. Keep getting "Invalid URL" message even  though I'm copying and pasting the url directly.

**Comment by Sorrow446** [comment]
What URL are you typing in and are you running from src?

**Comment by Cryptical1** [comment]
In Win10 cmd.  nugs_dl_x64.exe https://play.nugs.net/watch/livestreams/exclusive/35100

**Comment by Sorrow446** [comment]
Binaries are 11 commits behind. https://pixeldrain.com/u/o6eyjR6m
