### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by darkstar1972** [Sorrow446/Nugs-Downloader#36]
I am on a mac, and a total novice when it comes to working with Terminal. I am getting this error message for every url I have tried:

> Signed in successfully - Premium Streaming
> 
> Item 1 of 1:
> Invalid URL: https://play.nugs.net/watch/livestreams/exclusive/35104

Am I doing something wrong? My command is:

`./nugs_dl_mac_x64 https://play.nugs.net/watch/livestreams/exclusive/35104`

Thanks in advance

**Comment by darkstar1972** [comment]
I managed to get that first video downloaded by pasting the video ID number into a different link format. But now I am trying another video that seems to have a 6 digit ID and getting the same error message. The link in question is https://www.nugs.net/on/demandware.store/Sites-NugsNet-Site/default/Product-QueueVideo?pid=705424-WEBCASTVARIANT

**Comment by Sorrow446** [comment]
Same as https://github.com/Sorrow446/Nugs-Downloader/issues/34. You're running outdated binaries.
https://go.dev/dl/
`go run main.go structs.go <args/URLs>...` or `go build main.go structs.go`
