### ISSUE TITLE
Unavailable in your chosen format.

### ISSUE THREAD

**Issue by dr01dy** [Sorrow446/Nugs-Downloader#39]
Looking for a sanity check. Anyone else seeing "Unavailable in your chosen format." when you have your format set to 3. 
Example 13 of 15 tracks download will be in format 3 24-bit / 48 kHz MQA and then 2 of them will come down as 16-bit / 44.1 kHz FLAC
leading to a mixed bitrate album.

Just wondering

**Comment by Sorrow446** [comment]
Have seen this a few times on a few other streaming platforms. I can't check as my sub ran out a long time ago. You can check yourself on the mobile app, though.

**Comment by bisceaux** [comment]
> Looking for a sanity check. Anyone else seeing "Unavailable in your chosen format." when you have your format set to 3. Example 13 of 15 tracks download will be in format 3 24-bit / 48 kHz MQA and then 2 of them will come down as 16-bit / 44.1 kHz FLAC leading to a mixed bitrate album.

I saw the same thing a few days ago with a few shows.
