### ISSUE TITLE
24/96 flac?

### ISSUE THREAD

**Issue by PJAmerica** [Sorrow446/Nugs-Downloader#4]
Is there an option possible for the 24 bit 96khz? Just curious as Pearl Jam offers there shows in 24/96 flac-hd but can't download them through this app at that rate. Just 24/48.

**Comment by Sorrow446** [comment]
They don't have 24-bit non-MQA streams, sorry.

**Comment by PJAmerica** [comment]
> They don't have 24-bit non-MQA streams, sorry.

I see, thank you for your time.
