### ISSUE TITLE
Is it possible to download FLAC-HD - 24-bit / 96 kHz

### ISSUE THREAD

**Issue by bisceaux** [Sorrow446/Nugs-Downloader#40]
I don't see this as an option?  I know you can purchase the FLAC-HD.  And thank you for this tool!

**Comment by Sorrow446** [comment]
The only 24-bit streams they have are MQA, sorry. Gotta buy the non-MQA ones.

**Comment by bisceaux** [comment]
Thanks for the response and thanks for this tool! MQAs work for me :)
