### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by jbsmoke9** [Sorrow446/Nugs-Downloader#41]
No download format seems to be working.  Getting error messages such as:
Invalid URL
Item failed - the api didn't return a video manifest url

Everything was working a couple weeks ago.

**Comment by Sorrow446** [comment]
Post the links please unless it's every one.

**Comment by jbsmoke9** [comment]
Any link I try isnt working.  I downloaded most recent binaries and it still doesn't work.  Tried on multiple computers also.

Invalid URL: https://play.nugs.net/watch/livestreams/exclusive/35979

https://play.nugs.net/#/exclusive-livestreams/container/35978
Item failed.
the api didn't return a video manifest url

**Comment by Sorrow446** [comment]
The latest binaries are outdated is what I'm saying; it's not worth uploading new binaries for every commit I push. You can easily run or build from source.

Run:
`go run main.go structs.go <args>...`
Build binary:
`go build main.go structs.go`
