### ISSUE TITLE
Cant download a WEBCAST VARIANT type of livestream

### ISSUE THREAD

**Issue by maylortaylor** [Sorrow446/Nugs-Downloader#43]
I've been trying to download this video 
[(Billy Strings from 04/13/2024)](https://www.nugs.net/on/demandware.store/[Sites-NugsNet-Site](https://www.nugs.net/on/demandware.store/Sites-NugsNet-Site/default/NugsVideo-GetVideo?pid=731544-WEBCASTVARIANT)/default/NugsVideo-GetVideo?pid=731544-WEBCASTVARIANT)

but i keep getting an "Invalid URL" error.

**Comment by Sorrow446** [comment]
Will take a look tomorrow. Might be as simple as just adding a new regex string.
