### ISSUE TITLE
Exclusive Livestreams URL support

### ISSUE THREAD

**Issue by jjacobu** [Sorrow446/Nugs-Downloader#5]
Hello this tool works great and I am able to use it for catalog audio and video downloads. However I am getting Invalid URLs for the Exclusive Livestream URLs, examples: 

"https://play.nugs.net/#/exclusive-livestreams/container/30059"
"https://play.nugs.net/#/exclusive-livestreams/container/30119"
"https://play.nugs.net/#/exclusive-livestreams/container/30120"

I was able to download this URL: "https://play.nugs.net/#/videos/artist/1125/Billy%20Strings/container/28952"

**Comment by Sorrow446** [comment]
Livestreamed vids aren't supported yet, sorry. It wouldn't be a problem at all for me to implement it (just ts segments). Would you be willing to lend your account? Can't guarantee a date when I'll get round to it, though. Within a week from now I think.

**Comment by jjacobu** [comment]
I added you on Discord, let me share the credentials there. I could attempt a pull request if the code changes are simple

**Comment by Sorrow446** [comment]
Implemented https://github.com/Sorrow446/Nugs-Downloader/commit/9ee986a10fdf633070c7c8605a4f47465dade779.
