### ISSUE TITLE
why  not working

### ISSUE THREAD

**Issue by rinrinx** [Sorrow446/Nugs-Downloader#51]
C:\Users\rinrinx\Desktop\NUGS>nugs_dl_x64.exe https://play.nugs.net/browse/artist/1532

 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
          |___|

Signed in successfully - Premium Streaming

Item 1 of 1:
Invalid URL: https://play.nugs.net/browse/artist/1532

C:\Users\rinrinx\Desktop\NUGS>

**Comment by Sorrow446** [comment]
Use `https://play.nugs.net/#/artist/1532` instead.

**Comment by onelegbird** [comment]
Im on Ubuntu 
Signed in successfully - Premium Streaming

Item 1 of 1:
Invalid URL: https://play.nugs.net/release/37628

any ideas

**Comment by Sorrow446** [comment]
Yeah, run from source code. The binaries are outdated.

**Comment by rinrinx** [comment]
bro uptade binaries code windows

**Comment by Sorrow446** [comment]
https://workupload.com/file/6pBuqB6LYay

**Comment by rinrinx** [comment]
thank you so much
