### ISSUE TITLE
Trying to donwload link with "release"

### ISSUE THREAD

**Issue by Kamiloos** [Sorrow446/Nugs-Downloader#54]
Im trying to download https://play.nugs.net/release/30943 but all I've got from PowerShell is:

Signed in successfully - HiFi Streaming

Item 1 of 1:
Invalid URL: https://play.nugs.net/release/30943

Can anyone help?

**Comment by Sorrow446** [comment]
Running from source code or binaries? Binaries are months behind.

**Comment by Kamiloos** [comment]
Unfortunately I have little idea what You talking about ;) I found instructions on reddit, followed them here but to little success. I downloaded all files from main page od his site one by one to one folder, edit json with my login/pass, downloaded x64 exe file, run powershell and I manged to run downloader with with .\.

Nugs download starts, Show that I signed successfully Item 1 of 1, Invallid URL.

I managed to download whole artist catalog, so its working. Except for these "release" item from Nugs.

**Comment by Sorrow446** [comment]
You need to download and run from the src code. https://github.com/Sorrow446/Nugs-Downloader/archive/refs/heads/main.zip

Not gonna post a guide here as there's lots online, but I'll just compile the latest for you tomorrow if you haven't sorted it by then.

**Comment by Kamiloos** [comment]
Ok, somewhon I managed to do it :) Thanks :)
