### ISSUE TITLE
Downloading a release: "the api didn't return a track stream URL" error

### ISSUE THREAD

**Issue by conord** [Sorrow446/Nugs-Downloader#57]
Running on Macos and built from source. Trying to download `https://play.nugs.net/release/38566`. The app finds the album but fails with the above error on each track. Nothing is saved to disk. Any suggestions would be appreciated.

**Comment by dr01dy** [comment]
I would check your output. I verified it is working correctly. (mac, windows)

**Comment by conord** [comment]
Appreciate the quick response @dr01dy. Resolved the issue - I had the wrong account info in the config and was trying to download with an account that didn't have a subscription.
