### ISSUE TITLE
Invalid URL response when trying to download concert

### ISSUE THREAD

**Issue by Therdus** [Sorrow446/Nugs-Downloader#58]
Hi, I've tried both release 6 and the build you posted in response to issue #56 **(Edited to add: I also built from source to no avail)** but with either build I get a response of Invalid URL as shown in the screenshot below;

![image](https://github.com/user-attachments/assets/67ad3905-73f5-49f7-8d44-820d54d6bd9d)

For what it is worth, my account does have legitimate access to it as I paid to watch the gig (I don't have a Nugs sub). Any suggestions/assistance would be appreciated.

**Comment by joshuacant** [comment]
I'm getting the same error for the same show.

**Comment by JPHFanedits** [comment]
https://github.com/Sorrow446/Nugs-Downloader?tab=readme-ov-file#supported-media

You need to have FFmpeg and wrap the link in double quotes

**Comment by joshuacant** [comment]
When you say double quotes, do you mean " like in the screenshot? I think we're both doing that. In main.go there's a list of regexes which match valid URLs, and the URL we have for this show doesn't match any of the ones included.

**Comment by joshuacant** [comment]
This can be fixed by changing main.go:

Line 57: `var regexStrings = [11]string{`

Line 69: ``^https://www.nugs.net/on/demandware.store/Sites-NugsNet-Site/default/NugsVideo-GetStashVideo\?([a-zA-Z0-9=%&-]+$)`,`

Line 1678: `		case 9, 10:`

Build again and go. Worked for me. Generated an mp4 of size 3.08GB

**Comment by Sorrow446** [comment]
Because they keep adding new URL structures lol. I'll implement it into the last regex string later. Joshua's solution's fine.

**Comment by Sorrow446** [comment]
Fixed.
