### ISSUE TITLE
Error on downloading video

### ISSUE THREAD

**Issue by dixiecupdrinker** [Sorrow446/Nugs-Downloader#6]
Hi, not sure if I've missed an obvious config step.

I'm getting 'The API didn't return a video manifest URL' on the following. Windows version. Apple Auth which is working.

https://play.nugs.net/#/videos/artist/1238/The%20Rolling%20Stones/container/23708

**Comment by jjacobu** [comment]
It works for me, did you wrap the video in double quotes? 

PS C:\Program Files\ffmpeg-master-latest-win64-gpl> .\nugs_dl_x64.exe "https://play.nugs.net/#/videos/artist/1238/The%20Rolling%20Stones/container/23708"

 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
          |___|

Signed in successfully - nugs.net annual + 30 day trial

Item 1 of 1:
The Rolling Stones - 06/24/72 Tarrant County Convention Center, Fort Worth, TX
24.000 FPS, 5160 Kbps, 1080p (1920x1080)
0% @ 6.4 MB/s, 6.8 MB/2.9 GB

**Comment by dixiecupdrinker** [comment]
Yeah, this is what I get:

 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
          |___|

Signed in successfully - Itunes one month HiFi

Item 1 of 1:
The Rolling Stones - 06/24/72 Tarrant County Convention Center, Fort Worth, TX
Item failed.
The API didn't return a video manifest URL.
PS F:\downloads\nugs-downloader-main>

**Comment by Sorrow446** [comment]
Does your plan allow you to view the videos? It could be something to do with being an Apple account. I'd need you to send me a Fiddler session file privately to look into it more. Message me on Discord or Reddit please.

Sorrow#6826 / Sorrow446
