### ISSUE TITLE
Can you please add another URL format?

### ISSUE THREAD

**Issue by jbq416** [Sorrow446/Nugs-Downloader#61]
I noticed that this format (https://play.nugs.net/library/webcast/32400) is not working with the script anymore. I am unsure how to add a format on my own.

Thanks!

**Comment by Sorrow446** [comment]
Will do tomorrow. I've been waiting to push an update for more than a week, but my testers are slow.

**Comment by cfrancica** [comment]
Any luck with this? Using the suggested format doesn't seem to work for me (for a different webcast event I have access to). Thanks.

**Comment by ChristianVaughn** [comment]
Seems the alternative suggested URL doesn't work.

**Comment by Sorrow446** [comment]
Try `https://play.nugs.net/#/my-webcasts/32400-0-0`

**Comment by marksibert** [comment]
Just tried both of the suggested workarounds, and neither worked.

**Comment by marksibert** [comment]
I'm testing a fix now.  In main.go, I added line 69 (regexstrings array) :
	`^https://play.nugs.net/library/webcast/(\d+)$`,

Then changed the switch statement at the end of the file, and added '10' to the existing '4' logic:
		case 4, 10:
			itemErr = video(itemId, "", cfg, streamParams, nil, false)

 Seems to be working so far, but it'll take a bit for the download to finish and for me to verify it downloaded correctly. I haven't read through the code enough to fully understand it all -- just trying a quick & dirty fix.  If I get super motivated, perhaps I'll do an actual pull request, but I'm not really set up for that on this laptop.

**Comment by ChristianVaughn** [comment]
I just modified the code added the url, and put it in same case from the switch case to match the my-webcast url. seems to work. I used it on 2 different shows with that url format. I'm not sure if thats the proper way, but if it is do you want me to make a pull request with the url added?

**Comment by marksibert** [comment]
Yeah - I submitted the pull request after I got my other laptop set up for it. Thanks for verifying the fix.
