### ISSUE TITLE
Trouble getting a video to download

### ISSUE THREAD

**Issue by adampk17** [Sorrow446/Nugs-Downloader#62]
Hello -  I'm having a problem with downloading a video from Nugs - I don't know if this is another instance of a new URL format or something I am doing wrong.

Command I am using:

nugs_dl_x64.exe "https://play.nugs.net/watch/release/30955"

Result:

 _____                ____                _           _
|   | |_ _ ___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
| | | | | | . |_ -|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_|___|___|_  |___|  |____/|___|_____|_|_|_|___|__,|___|___|_|
          |___|

Signed in successfully - Premium Streaming

Item 1 of 1:
Invalid URL: https://play.nugs.net/watch/release/30955

**Comment by jrdean** [comment]
Modify your link by removing "/watch" from the middle. So for this example it was 
https://play.nugs.net/watch/release/30955 - modified to:
https://play.nugs.net/release/30955
By default this it will pull the audio tracks, so you need to add " --force-video" if you're after the video.

Command to use:
nugs_dl_x64.exe "https://play.nugs.net/release/30954" --force-video

**Comment by Sorrow446** [comment]
The pre-compiled binaries are more than a year behind the code I should add.

**Comment by adampk17** [comment]
I downloaded the individual files from github, I hope that takes care of the comment about the pre-compiled binarys?

But when I try that command you gave me I get this:

![image](https://github.com/user-attachments/assets/41126630-82b0-46b9-ad2f-dbae9c709c39)

**Comment by jrdean** [comment]
I forgot that the pre-compiled binaries are out of date and don't have the --force-video flag at that time. You need to run or compile the source that you downloaded. Here's a link where Sorrow446 explains what to do. 
https://github.com/Sorrow446/Nugs-Downloader/issues/41#issuecomment-1967849145

**Comment by adampk17** [comment]
Thank you all -  I was able to get the content I was after.
