### ISSUE TITLE
Only Downloading Livestream 30119

### ISSUE THREAD

**Issue by levle99** [Sorrow446/Nugs-Downloader#8]
No matter what link I paste in for the live-streams, it is trying to download https://play.nugs.net/#/exclusive-livestreams/container/30119.

I tried https://play.nugs.net/#/exclusive-livestreams/container/30120 , https://play.nugs.net/#/exclusive-livestreams/container/30137 , and https://play.nugs.net/#/exclusive-livestreams/container/30138 which all tried to download 30119 instead.

**Comment by Sorrow446** [comment]
Fixed. Silly mistake on my part, sorry.
