### ISSUE TITLE
nugs_dl_mac_x64 fails with segmentation fault on macOS Ventura 13.0

### ISSUE THREAD

**Issue by awilkes** [Sorrow446/Nugs-Downloader#9]
After upgrading to Ventura, the x64 binary for macOS fails with a segmentation fault:

```
% ./nugs_dl_mac_x64 https://play.nugs.net/index.html#/catalog/recording/XXXXX
zsh: segmentation fault  ./nugs_dl_mac_x64 https://play.nugs.net/index.html#/catalog/recording/XXXXX
```

(I tried the ARM version in the past, but it failed with an error I don't recall. Should I use that instead?)

However, I was able to get around this by compiling from source:

```
% GOOS=darwin GOARCH=amd64 go build
% ./main https://play.nugs.net/#/catalog/recording/XXXXXX
# success
```

**Comment by Sorrow446** [comment]
Those binaries are months old so everyone should be running from source instead. `darwin` and `amd64` are what I use for building Mac binaries, Go doesn't support building 32-bit for Mac.

**Comment by awilkes** [comment]
Thanks.
